### ISSUE TITLE
No emails processed with newer versions of Joplin

### ISSUE THREAD

**Issue by djvreeman** [joplin/plugin-email#30]
I've been using this email plugin successfully for several months. Around version 2.12.19 of Joplin (I'm not exactly sure of the version), it stopped being able to process any emails from the selected folder. Authentication to the email server works fine.

In the logs, everything looks ok:
PluginService: "Loading plugin from /Users/dvreeman/.config/joplin-desktop/cache/Bishoy.EmailPlugin"
joplin.plugins: "Finished running onStart handler: Bishoy.EmailPlugin (Took 3289ms)"

However, there are a few issues in the Dev Tools Console output -- I can't determine their significance:

<img width="547" alt="Screenshot 2024-01-01 at 6 45 08 PM" src="https://github.com/joplin/plugin-email/assets/25436589/e5f0f152-715d-4d62-bab0-f21282a113cc">

**Comment by chopstik** [comment]
Similar issue to https://github.com/joplin/plugin-email/issues/28

**Comment by djvreeman** [comment]
After more investigation and writing a python script to do similar email processing as this plugin, I've discovered that the issue was on problematic email in the queue. That email hangs the plugin and kills the processing for all subsequent ones. 

So what looked like an issue with a new Joplin version was really just stuck on a particularly formatted (or ill-formatted) message. I can't tell exactly what about the message causes the plugin (and processing with python's BeautifulSoup library) to hang (it does have the deprecated <center> tags). But the problem is not as described here, so I am closing this ticket.

**Comment by chopstik** [comment]
Any chance you could post a gist of the Python script you used to check the email @djvreeman? Be great to see if its an email that's causing the issues I'm seeing with email retrieve.

**Comment by djvreeman** [comment]
In case it's helpful, here's a link to my [python script for processing unread messages in an IMAP inbox folder and turning them into Joplin notes](https://github.com/djvreeman/joplin-utils/blob/main/joplin-process-email.py). It reads the IMAP and Joplin API info from a config file, an [example of which is here.](https://github.com/djvreeman/joplin-utils/blob/main/config-example.ini).

As I mentioned above, this script too dies on the problematic email in my queue, but it allowed me to figure out what was going on.
